### PR TITLE
Feature/add python3.12 drop python3.7

### LINKED ISSUE #111: python3.12
Tests run **successfully** on python3.12, so the only step to make is adding python3.12 to the `ci` test job (and somehow updating supported versions in README).

Also, it looks like the time has come to drop python3.7,

### PR DESCRIPTION
**Pull request by maxzhenzhera**
Closes #111

### CODE REVIEW

**Comment by maxzhenzhera** [comment]
Omg, I made smth bad for python3.8
I think it is a question of imports

**Comment by maxzhenzhera** [comment]
Hmm, I believed that `get_origin`, `get_args` have become available in python3.8 and it is safe to them use just from std...)

**Comment by adriangb** [comment]
> Hmm, I believed that `get_origin`, `get_args` had become available in python3.8 and it is safe to use them just from std...)

I don't think so: https://github.com/python/typing_extensions/blob/b6318ab4b4777a38b468eef7aae97061c283eb8d/src/typing_extensions.py#L1175-L1177

**Comment by maxzhenzhera** [comment]
> I don't think so: https://github.com/python/typing_extensions/blob/b6318ab4b4777a38b468eef7aae97061c283eb8d/src/typing_extensions.py#L1175-L1177

Okay, I see.
Thanks for pointing that out.

**Comment by maxzhenzhera** [comment]
@adriangb Please, review

**Review by adriangb — APPROVED** [review]

**Pull request merged**
