### PR TITLE
Fix/callable class generator not handled

### LINKED ISSUE #106: enhancement: dependent call should handle class __call__ when it is generator
# Example

Here I use factory (dependent call) as a configurable class with `__call__`:
https://github.com/maxzhenzhera/di/blob/5302c792bad2f3ee0dc8fae6116756e088b95f87/docs_src/bug_callalbe_class_instance_not_handled_as_factory.py

```python
    with container.enter_scope("request") as state:
        db = solved.execute_sync(executor=SyncExecutor(), state=state)
        print(db)  # <generator object PostgresFactory.__call__ at 0x7f52f19657e0>
```

But `__call__` is not handled and I got just a raw generator.

# Workaround

It works if I simply put `__call__` as dependent call:
```python3
    container.bind(
        bind_by_type(
            Dependent(
                PostgresFactory(db_config).__call__,
                scope="request",
            ),
            DBProtocol,
        ),
    )
```

Result:
```python
    with container.enter_scope("request") as state:
        db = solved.execute_sync(executor=SyncExecutor(), state=state)
        print(db)
        # Postgres init-ed
        # <__main__.Postgres object at 0x7f1d09713400>
        # Postgres closed
```

---

Handling of this case fixed in one Fastapi`s PR: https://github.com/tiangolo/fastapi/pull/1365

### PR DESCRIPTION
**Pull request by maxzhenzhera**
Closes #106

### CODE REVIEW

**Comment by maxzhenzhera** [comment]
# Check Version Bump
I did a few PRs and I don't know how to bump new versions concurrently

**Comment by maxzhenzhera** [comment]
# Tests
Again `Error uploading to [https://codecov.io:](https://codecov.io/)`
As in #103

**Comment by maxzhenzhera** [comment]
> In many places anyio.Event.set() is not awaited:

I'm sorry for being wrong. Actually, my PyCharm highlighted it as `await`able (but looking in the source I understood that it is deprecated).

> I haven't paid a lot of attention to how this works and how it should be - but I randomly changed sync1 and sync2 in multiple mark places => and tests haven't failed.

As I found out - `sync` params just obsolete params: https://github.com/adriangb/di/commit/e43def722d1f3d6a5fce29ae5e367930c615288c
So, I fully removed these params from test `parametrize`.

---

Some additional notes about `test_concurrency_async`:
- with removing `sync_to_thread` (https://github.com/adriangb/di/commit/f7051c1ca31f9f0fa2653ae05ff6b56b3160fada, https://github.com/adriangb/di/commit/e43def722d1f3d6a5fce29ae5e367930c615288c) you added `as_async` wrapper (https://github.com/adriangb/di/commit/f7051c1ca31f9f0fa2653ae05ff6b56b3160fada#diff-a1a77ec455d6596eaee848c37661eed959a83b787427364bc494ae32147ea24b)
It is used only in `tests/` to **wrap sync callables**.


- **wrap sync callables** - this is another point
As I understand, this test serves as verification that concurrent async execution **just works**.
And `as_async` wrapping proves that concurrent async execution works with sync callables running in `anyio` threadpool (it is actually what `as_async` does) - and my question is there any reason to do this?
Because for me reading this code introduces some ambiguity and misunderstanding.

---

So, I propose:
- Move `as_async` (https://github.com/adriangb/di/blob/main/di/_utils/concurrency.py) to `tests/`
- Add docstring to `test_concurrency_async` to explain the role of this case 
(possibly with removing `as_async` wrappings if not reason for it)

**Comment by maxzhenzhera** [comment]
@adriangb, please review

**Review by adriangb — APPROVED** [review]

**Pull request merged**
